"use server";
import { GoogleGenerativeAI, DynamicRetrievalMode } from "@google/generative-ai";

const geminiApiKey = process.env.GEMINI_API_KEY;

if (!geminiApiKey) {
  throw new Error("GEMINI_API_KEY environment variable is not set.");
}
const systemInstruction = `You are a helpful AI chatbot specialized in finance and the economy. Your primary focus is to discuss topics such as investment strategies, market trends, and financial planning. 
  You can also engage in basic casual conversation, specifically responding to greetings and farewells or similar simple remarks. If a user asks about a topic outside of finance, 
  politely steer the conversation back to finance-related subjects. For example, you can say something like, 'That's an interesting topic, but let's get back to finance. 
  Is there anything you'd like to discuss about investments or financial planning?' or 'While that's not my area of expertise, I can definitely help you with questions about market trends or investment strategies.' 
  Keep your responses concise and helpful within the scope of finance and basic greetings/farewells. Important: keep your responses under 100 words. Responses should be in plain text, emojis are acceptable.`

const genAI = new GoogleGenerativeAI(geminiApiKey);
const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash", systemInstruction: systemInstruction, })
const chat = model.startChat({
  history: [],
  generationConfig: {
    temperature: 0.0,
    maxOutputTokens: 200,
  },
  tools: [{google_search: { } }]
});

let isAwaitingResponse = true;

// REAL function
export async function generateText(prompt: string, onChunk?: (chunk: string) => void): Promise<string> {
  isAwaitingResponse = true;
  try {
    const result = await chat.sendMessageStream(prompt)
    let text = "";

    for await (const chunk of result.stream) {
      const chunkOfText = await chunk.text();
      text += chunkOfText;
      onChunk?.(chunkOfText);
    }

    isAwaitingResponse = false;

    return text;
  } catch (error: any) {
    console.error("Error generating text:", error);
    throw new Error(error.message); 
  }
}



// Mock function
export async function generateInvestmentProfile(answers: Record<string, string>) {
  // In a real app, this would use the AI SDK to generate a profile based on answers
  // For demo purposes, we'll return a mock profile

  try {
    // This is a simulation - in a real app, we would use the answers to generate a prompt
    const prompt = `
      Generate an investment profile based on these answers:
      Risk tolerance: ${answers.risk_tolerance}
      Financial goals: ${answers.financial_goals}
      Investment experience: ${answers.investment_experience}
      Time horizon: ${answers.time_horizon}
      Income range: ${answers.income_range}
    `

    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 1500))

    // Return mock data - in a real app, this would be generated by the AI
    return {
      type: "Balanced Growth Investor",
      description:
        "You seek a balance between growth and stability, with a moderate risk tolerance and long-term perspective.",
      allocation: [
        { name: "Stocks", value: 50, color: "#8b5cf6" },
        { name: "Bonds", value: 35, color: "#0ea5e9" },
        { name: "Alternative Investments", value: 10, color: "#f59e0b" },
        { name: "Cash", value: 5, color: "#10b981" },
      ],
      explanation:
        "This balanced allocation provides growth potential through stocks while maintaining stability with bonds. The small allocation to alternative investments adds diversification, and the cash reserve gives you flexibility for opportunities or emergencies.",
    }
  } catch (error) {
    console.error("Error generating investment profile:", error)
    throw error
  }
}

// Mock function to simulate AI assistant responses
// export async function askAiAssistant(question: string) {
//   try {
//     // In a real app, this would use the AI SDK to generate a response
//     // For demo purposes, we'll use a simple implementation

//     // This is a simulation - in a real app, we would use the AI SDK
//     /*
//     const { text } = await generateText({
//       model: openai("gpt-4o"),
//       prompt: question,
//       system: "You are an AI investment assistant helping a user with their investment questions. Provide helpful, accurate, and concise responses."
//     });
//     return text;
//     */

//     // Simulate API delay
//     await new Promise((resolve) => setTimeout(resolve, 1000))

//     // Simple response logic for demo purposes
//     if (question.toLowerCase().includes("etf")) {
//       return "ETFs (Exchange-Traded Funds) are investment funds traded on stock exchanges. They hold assets like stocks, bonds, or commodities and typically track an index. ETFs offer diversification, low expense ratios, and tax efficiency, making them popular for both beginners and experienced investors."
//     } else if (question.toLowerCase().includes("risk")) {
//       return "Investment risk refers to the possibility of losing money or not meeting financial goals. Different investments carry different levels of risk - generally, higher potential returns come with higher risk. Diversification across asset classes can help manage risk in your portfolio."
//     } else if (question.toLowerCase().includes("bond")) {
//       return "Bonds are debt securities where you lend money to an issuer (like a government or corporation) in exchange for periodic interest payments and the return of the bond's face value when it matures. They're generally considered lower risk than stocks but offer lower potential returns."
//     } else if (question.toLowerCase().includes("stock")) {
//       return "Stocks represent ownership in a company. When you buy a stock, you're purchasing a share of the company's assets and earnings. Stocks offer growth potential through price appreciation and dividends, but they typically come with higher volatility than bonds."
//     } else if (question.toLowerCase().includes("diversif")) {
//       return "Diversification is a risk management strategy that involves spreading your investments across various asset classes, industries, and geographic regions. The goal is to reduce exposure to any single investment's risk and smooth out returns over time. A well-diversified portfolio might include stocks, bonds, real estate, and perhaps alternative investments."
//     } else if (question.toLowerCase().includes("portfolio")) {
//       return "Your investment portfolio should align with your financial goals, risk tolerance, and time horizon. Based on your profile, a balanced approach with a mix of stocks for growth and bonds for stability appears appropriate. Consider regular rebalancing to maintain your target allocation as market values change."
//     } else {
//       return "That's a great question about investing. As you continue your investment journey, remember that diversification, long-term thinking, and aligning your investments with your goals and risk tolerance are key principles for success. Would you like more specific information about any particular investment topic?"
//     }
//   } catch (error) {
//     console.error("Error getting AI response:", error)
//     throw error
//   }
// }

// Function to search for investment terms and concepts
export async function searchInvestmentTerms(query: string) {
  try {
    // In a real app, this would call an API to search for investment terms
    // For demo purposes, we'll simulate a response

    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 1000))

    // Return mock data
    return {
      results: [
        {
          id: "1",
          title: "What is an ETF?",
          snippet:
            "Exchange-traded funds (ETFs) are a type of investment fund and exchange-traded product, i.e., they are traded on stock exchanges...",
          url: "https://example.com/etf-guide",
          source: "article",
        },
        {
          id: "2",
          title: query + " Definition",
          snippet: "A comprehensive explanation of " + query + " in the context of investing and finance.",
          url: "#",
          source: "definition",
        },
      ],
    }
  } catch (error) {
    console.error("Error searching investment terms:", error)
    throw error
  }
}

// Function to get market data
export async function getMarketData() {
  try {
    // In a real app, this would call an API to get market data
    // For demo purposes, we'll simulate a response

    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 1000))

    // Return mock data
    return {
      indices: [
        {
          id: "sp500",
          name: "S&P 500",
          value: 5123.45,
          change: 23.45,
          changePercent: 0.46,
        },
        {
          id: "dow",
          name: "Dow Jones",
          value: 38765.32,
          change: -125.68,
          changePercent: -0.32,
        },
      ],
      trending: [
        {
          id: "1",
          symbol: "AAPL",
          name: "Apple Inc.",
          price: 175.5,
          change: 2.75,
          changePercent: 1.59,
        },
        {
          id: "2",
          symbol: "TSLA",
          name: "Tesla, Inc.",
          price: 245.75,
          change: 12.5,
          changePercent: 5.36,
        },
      ],
    }
  } catch (error) {
    console.error("Error getting market data:", error)
    throw error
  }
}